- hosts: all
  become: yes
  tasks:
    - name: add redis mirror key
      apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x136221EE520DDFAF0A905689B9316A7BC7917B12
    - name: add redis mirror
      apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise main'
    - name: install redis
      apt: name=redis-server=3:3.0.7-1chl1~precise1
    - name: check if old redis server is running
      stat: path=/etc/init.d/redis-server
      register: redis_server
    - name: stop old redis server
      service: name=redis-server state=stopped enabled=no
      when: redis_server.stat.exists
    - name: remove old redis configs
      file: dest="{{ item }}" state=absent
      with_items:
        - /etc/redis/redis.conf
        - /etc/init.d/redis-server
    - name: add config for each redis server
      template: src=etc/redis.conf dest="/etc/redis/redis_{{ item }}.conf"
      with_items:
        - 6379
        - 6380
        - 6381
      notify:
        - restart redis instance
    - name: create redis instance working directories
      file: dest="/var/lib/redis/{{ item }}" state=directory
      with_items:
        - 6379
        - 6380
        - 6381
    - name: create redis instance init scripts
      template: src=etc/redis.init dest="/etc/init.d/redis-server-{{ item }}" mode=0755
      with_items:
        - 6379
        - 6380
        - 6381
      notify:
        - restart redis instance
  handlers:
    - name: restart redis instance
      service: name="redis-server-{{ item }}" enabled=yes state=restarted
      with_items:
        - 6379
        - 6380
        - 6381
