- hosts: all
  become: yes
  tasks:
    - name: add redis mirror key
      apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x136221EE520DDFAF0A905689B9316A7BC7917B12
    - name: add redis mirror
      apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise main'
    - name: install redis
      apt: name=redis-server=3:3.0.7-1chl1~precise1
