#!/bin/bash

for arg in "$@"
do
    case $arg in
        --json)
            export USE_JSON=t
        ;;
        --pickle)
            export USE_PICKLE=t
        ;;
        --msgpack)
            export USE_MSGPACK=t
        ;;
        --yaml)
            export USE_YAML=t
        ;;
    esac
done

USE_RABBITMQ=t celery -A app worker -n rabbitmq_worker_$RANDOM
